apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-blue
  labels:
    app: django-messaging
    version: "1.0" # Blue version
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1 # Number of extra pods allowed during update
      maxUnavailable: 0 # Ensures full capacity during rollout
  selector:
    matchLabels:
      app: django-messaging
      version: "1.0"
  template:
    metadata:
      labels:
        app: django-messaging
        version: "1.0"
    spec:
      containers:
        - name: django-app
          image: your-django-image:2.0 # Updated image version
          ports:
            - containerPort: 8000
          readinessProbe:
            httpGet:
              path: /health/
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5

            envFrom:
              - configMapRef:
                  name: django-config
