#!/bin/bash

set -e

echo "Checking if Minikube is installed..."
if ! command -v minikube &> /dev/null; then
  echo "Minikube not found. Please install Minikube first."
  exit 1
fi

if ! minikube status | grep -q "Running"; then
    echo "Starting Minikube cluster with Docker driver..."
    minikube start --driver=docker
    echo "Minikube cluster started"
else
    echo "Minikube cluster already running"
fi

echo "Verifying that the Kubernetes cluster is running..."
kubectl cluster-info

echo "Nodes: "
kubectl get nodes

echo "Pods in all namespaces:"
kubectl get pods -A

echo "Retrieve current pods in all namespaces..."
kubectl get pods --all-namespaces
