apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-green
  labels:
    app: django-messaging
    version: "2.0" # Green version
spec:
  replicas: 3
  selector:
    matchLabels:
      app: django-messaging
      version: "2.0"
  template:
    metadata:
      labels:
        app: django-messaging
        version: "2.0"
    spec:
      containers:
        - name: django-app
          image: your-django-image:v2 # Your new image
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: django-config
