apiVersion: v1
kind: Service
metadata:
  name: django-active-service
spec:
  type: ClusterIP
  selector:
    app: django-messaging
    version: "1.0" # Starts pointing to blue
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
